export const SYSTEM_PERSONA = `You are a senior architect, urbanist, and interior designer with 20 years of experience, specialized in generating photorealistic AI image prompts for architectural renders. You have deep knowledge of 3D rendering, lighting techniques, materials, spatial composition, and photographic principles. You always write prompts in English, highly technical, optimized for Midjourney, DALL-E 3, and Adobe Firefly. Your prompts are precise, vivid, and produce award-winning architectural visualizations.`
 
export const RENDER_PROMPTS: Record<string, string> = {
 
  // ─────────────────────────────────────────────
  // TIPO DE RENDER
  // ─────────────────────────────────────────────
 
  render_geral: `Transform this 3D print into an ultra-photorealistic image, as if captured by a professional architectural photographer using a high-end DSLR/full-frame camera.
Mandatory rules (do not violate): maintain 100% of the original project without adding, removing or modifying any element. Do not alter materials, textures, colors, furniture, volumetry or layout. Do not replace cladding or reinterpret finishes. Do not add decorative objects, plants, people, extra lighting or artistic effects.
Visual objective: 100% photographic appearance, completely eliminating any render or illustration aspect. Natural and realistic lighting coherent with the original environment. Soft and physically correct shadows. Textures exactly matching the model, only with camera realism (sharpness, microcontrast and depth). Perspective and framing identical to the original print.
Technical quality: 4K resolution, high level of detail, slight realistic depth of field where applicable, neutral white balance and correct exposure.
Final expected result: an image indistinguishable from a real photograph, maintaining absolute fidelity to the original project, without any creative interference. IMPORTANT: Do not alter any texture or format of the original base image.`,

  render_externo: `Transform the SketchUp print into a photorealistic image of a residential or commercial facade, with the appearance of professional architectural photography. Preserve 100% of the original volumetry, proportions, and design, without altering any architectural forms, openings, or compositional elements. Apply realistic materials and cladding with high-resolution textures, natural reflections, subtle imperfections, and realistic color variation across surfaces. Render surrounding landscape, ground plane, and contextual elements with photographic fidelity. Adjust exposure, white balance, and contrast to simulate a full-frame DSLR camera with a 24mm tilt-shift lens, corrected verticals. Include realistic details such as slight material aging, subtle depth of field, and photographic sharpness throughout. Style: hyper-realistic, contemporary architecture, ultra-high quality, render indistinguishable from a real photograph. IMPORTANT: Do not alter any texture or format of the original base image.`,

  render_interno: `Transform the SketchUp print into a photorealistic interior architectural image, with the appearance of professional interior design photography. Preserve 100% of the spatial layout, ceiling heights, openings, furniture placement, and all architectural proportions without any modification. Apply realistic finishes to floors, walls, ceilings, and surfaces with high-resolution textures, accurate material reflectivity, and subtle surface imperfections. Render furniture, lighting fixtures, and decor elements with full photographic detail. Adjust exposure, white balance, and depth of field to simulate a DSLR camera with a 24mm wide-angle lens at eye level, 1.2m height. Include realistic details such as soft shadows cast by objects, material grain visible at close range, and natural light interacting with interior surfaces. Style: hyper-realistic, contemporary interior architecture, ultra-high quality, render indistinguishable from a real photograph. IMPORTANT: Do not alter any texture or format of the original base image.`,
 
  render_aereo: `Transform the SketchUp print into a photorealistic aerial image of the full site, with the appearance of professional drone photography. Preserve 100% of the site layout, roof geometry, landscaping footprint, and all architectural volumes without any alteration. Apply realistic rooftop materials, pavement textures, vegetation, and surrounding context with high-resolution aerial-scale fidelity. Render the full property boundary, neighboring context, and street level visible from above. Adjust exposure and color grading to simulate a DJI Mavic 3 Pro camera at 80 meters altitude, 45-degree oblique angle, with correct perspective foreshortening. Include realistic details such as rooftop HVAC elements, parapet shadows, tree canopy depth, and vehicle scale. Style: hyper-realistic, cinematic drone photography, ultra-high quality, render indistinguishable from a real aerial photograph. IMPORTANT: Do not alter any texture or format of the original base image.`,
 
  render_detalhe: `Transform the SketchUp print into a photorealistic architectural detail image, with the appearance of professional macro architectural photography. Preserve 100% of the original geometry of the detail being shown — material junction, window reveal, structural connection, facade joint, or canopy edge — without modifying any form or proportion. Apply high-resolution material textures with sub-millimeter surface detail, visible grout lines, weld marks, material grain, and subtle weathering. Render surrounding context falling into soft bokeh. Adjust exposure and depth of field to simulate a DSLR camera with an 85mm macro lens at F2.0, with sharp focus plane on the primary detail. Include realistic details such as raking light revealing surface relief, micro-texture variation, and realistic material aging. Style: hyper-realistic, precision architectural detail, ultra-high quality, render indistinguishable from a real close-up photograph. IMPORTANT: Do not alter any texture or format of the original base image.`,

  render_corte: `Transform the SketchUp print into a photorealistic architectural section render, with the appearance of a professional cut-through visualization. Preserve 100% of the section geometry, floor-to-floor heights, slab thicknesses, wall depths, stair configurations, and spatial relationships between internal environments as drawn. The cut plane must remain exactly as defined in the original — do not reinterpret or close any opening created by the section cut. Apply realistic materials and finishes to all exposed interior surfaces, structural elements, flooring layers, ceiling treatments, and furniture visible through the cut. Render the cut face itself with accurate material cross-sections — concrete mass, wall build-up, insulation layers, floor finish depth — all legible at architectural scale. Interior lighting conditions rendered accurately per room function. Exterior context visible beyond the section cut rendered with photographic depth. Adjust camera to simulate a DSLR positioned perpendicular to the cut plane, orthographic or near-orthographic perspective, full section height in frame. Style: hyper-realistic, technical architectural section, ultra-high quality, render indistinguishable from a real professional section visualization. IMPORTANT: Do not alter any texture or format of the original base image.`,
 
  planta_humanizada: `Transform the SketchUp or CAD floor plan print into a photorealistic humanized plan render, with the appearance of a professional top-down architectural visualization. Preserve 100% of the original floor plan geometry — wall positions, room dimensions, door and window openings, circulation paths, and spatial layout — without any modification whatsoever. Apply realistic materials and textures viewed from directly above — floor finishes, tile patterns, wood grain direction, carpet texture, stone slabs — all rendered with accurate top-view perspective and correct material scale. Furniture, fixtures, and fittings present in the plan rendered with photographic top-view fidelity, including shadows cast downward onto floor surfaces by a simulated overhead light source at low angle to create depth and volume. Vegetation elements such as trees, shrubs, and lawn rendered in top-view with natural color and texture variation. Water features rendered with accurate top-view reflectivity. Human figures, vehicles, and scale references included where present in the original. Walls rendered with accurate thickness, fill material, and top-view section treatment. Adjust rendering to simulate a perfectly vertical overhead camera, no perspective distortion, even diffuse illumination from above. Style: hyper-realistic humanized floor plan, ultra-high quality, professional architectural presentation standard. IMPORTANT: Do not alter any texture or format of the original base image.`,

  // ─────────────────────────────────────────────
  // PERÍODO DO DIA / ILUMINAÇÃO
  // ─────────────────────────────────────────────

  diurno: `Apply bright midday natural daylight with the sun at high elevation, approximately 65 degrees above the horizon. Color temperature at 5600K. Cast hard directional shadows from overhangs, window frames, louvres, and vegetation onto facade and ground surfaces. Sky rendered as clear deep blue with one or two scattered cumulus clouds. Full ambient bounce light from ground plane and surrounding surfaces filling shadow areas with soft secondary illumination. All facade materials receiving direct solar radiation with accurate specular response. Adjust exposure to simulate correct midday DSLR settings, no overexposure on lit surfaces, detail retained in shadow zones.`,

  entardecer: `Apply golden hour natural lighting with the sun positioned at approximately 8 degrees above the horizon, color temperature dropping to 2800K. All west and south-facing surfaces bathed in warm amber and orange light. East-facing surfaces in cool blue shadow with soft sky fill. Cast long raking shadows stretching across ground plane, emphasizing surface texture and relief. Sky rendered as a gradient from deep burnt orange at the horizon through magenta to cobalt blue at zenith. Subtle volumetric light rays visible where sun passes through vegetation or openings. Specular highlights intensified on glazed surfaces and water features. Adjust exposure to simulate DSLR settings capturing full dynamic range from bright sky to shaded areas.`,

  noturno: `Apply full nighttime lighting conditions with deep indigo and near-black sky. All exterior artificial light sources fully active — facade wash lighting, soffit downlights, landscape uplights on trees and plants, pathway lights at grade, and pool or water feature underwater lighting where present. Interior spaces glowing warmly through glazed surfaces, casting soft interior light onto adjacent exterior floor planes. Render all light sources with natural bloom and falloff, no clipping or overexposure on bulb sources. Deep shadow zones with only soft ambient spill from nearby fixtures. Sky with faint star texture and possible moonlight contribution as secondary fill. Color temperature of artificial sources between 2700K and 3000K. Adjust camera settings to simulate long-exposure DSLR night photography, low noise, natural light balance.`,

  nublado: `Apply overcast sky lighting conditions with a full cloud cover acting as a large natural diffusion panel. Color temperature at 6500K. Zero hard shadows anywhere in the scene — all surfaces receive soft, directionless, even illumination simultaneously. Sky rendered as a uniform silver-white overcast layer with subtle tonal variation between cloud masses. All material colors rendered at their most accurate and saturated without the interference of direct sunlight or shadow contrast. Slight cool blue-gray tone in ambient light. Ground plane receiving soft bounce from sky above. Adjust exposure to simulate a DSLR in flat-light conditions, balanced histogram, no blown highlights, full shadow detail retained. Ideal conditions for material legibility and architectural clarity.`,

  chuva: `Apply active rainstorm atmosphere with a dark mid-gray stratocumulus overcast sky. Render fine rain streaks as diagonal motion blur across the full frame, density consistent with moderate rainfall. All horizontal surfaces — pavement, deck, coping, car roofs, window sills — covered in a thin reflective water film producing mirror-like specular reflections of sky, facade, and light sources. Puddles accumulating in low points and joints with concentric ripple patterns. Facade glazing streaked with water rivulets running vertically. Ambient light flat and desaturated at 6800K, slightly underexposed to reinforce storm mood. All artificial light sources where present rendered with intensified bloom from moisture in air. Adjust camera settings to simulate DSLR in wet conditions, slight atmospheric haze reducing contrast of distant elements.`,

  amanhecer: `Apply pre-sunrise dawn lighting with the sun not yet above the horizon. Sky rendered as a layered gradient — deep charcoal at zenith transitioning through rose pink, peach, and pale lavender descending toward the horizon where a warm backlit glow is present. Overall scene lit by soft 4200K indirect sky dome light with no direct solar shadows. Low atmospheric ground haze at 0.5 to 1.0 meter height partially obscuring base of trees and ground plane. Dew visible on vegetation, horizontal surfaces, and glazing. Long horizontal cloud layers at horizon catching earliest light in gold and amber. All facade surfaces receiving cool, soft, directional fill from the bright horizon zone. Adjust camera settings to simulate DSLR at dawn, slightly lifted shadows, gentle highlight rolloff, high atmospheric depth.`,

  // ─────────────────────────────────────────────
  // ELEMENTOS DO AMBIENTE
  // ─────────────────────────────────────────────

  piscina: `Convert this 3D print into a professional ultra-realistic architectural photograph as if captured by a specialized architectural photographer using a high-end DSLR/full-frame camera, 4K resolution.
Swimming pool area: masonry pool with realistic tile or mosaic cladding, crystal clear water with transparency, reflections and gentle natural undulation. Daytime scene with blue clear sky, natural sunlight and soft natural shadows, realistic solar lighting with precise physical reflections on pool water. Specular reflections, subtle caustics and light variation according to sun angle.
External deck in natural wood or porcelain tile with texture and real wear. Realistic sun loungers, natural fabric umbrella and sophisticated external furniture. Absolute restriction: do not alter architecture, volumetry, proportions or layout of the original project. IMPORTANT: Do not alter any texture or format of the original base image.`,

  jardim: `Professional tropical landscaping, lush manicured garden, ornamental plants, curated green areas, mature trees providing natural shade. Realistic vegetation with natural colors, physically correct leaf textures, subtle imperfections and natural scale.
Natural lighting coherent with environment, realistic shadows cast by vegetation, depth and layering in planting composition. Landscape photography style, high level of botanical detail, photorealistic organic materials. IMPORTANT: Do not alter any texture or format of the original base image.`,
 
  area_gourmet: `Covered outdoor gourmet area, pergola or shade structure, built-in BBQ kitchen, outdoor dining setup with table and chairs, ambient string lighting for atmosphere.
Realistic materials: natural wood for pergola and furniture, natural stone or porcelain countertops, stainless steel appliances. Warm and balanced lighting coherent with gourmet environment. High-end lifestyle photography style, sophisticated residential ambiance. IMPORTANT: Do not alter any texture or format of the original base image.`,
 
  garagem: `Vehicle access driveway, garage entrance portal, paved approach with realistic floor texture. Architectural car portal detail with precise material finishes. Realistic vehicles where visible, natural lighting coherent with facade.
Professional architectural photography style focused on the entrance composition, high level of material detail, real photo appearance. IMPORTANT: Do not alter any texture or format of the original base image.`,
 
  deck: `Natural hardwood deck with rich timber grain texture, realistic weathering and tonal variation of real wood. Outdoor lounge furniture integrated naturally into the deck composition.
Seamless indoor-outdoor transition visible in the framing. Warm natural lighting enhancing wood tones, physically correct reflections on smooth surfaces, depth of field focused on the deck material detail. IMPORTANT: Do not alter any texture or format of the original base image.`,
 
  iluminacao_cenica: `Dramatic architectural uplighting on facade, precision spotlights highlighting architectural volumes, garden path lighting with subtle glows, LED strip accents on architectural details, light sculpture effect through deliberate shadow and light contrast.
Warm white (3000K) lighting temperature throughout, balanced without blown highlights, sophisticated nighttime atmosphere. IMPORTANT: Do not alter any texture or format of the original base image.`,
 
  nevoa: `Morning atmospheric fog, ethereal mist layers around lower vegetation and ground, soft depth haze reducing background visibility naturally, dreamlike and serene quality.
Diffused soft lighting coherent with foggy morning atmosphere, muted color palette with cool blue-grey tones, reduced contrast and visibility depth creating natural layers of depth. IMPORTANT: Do not alter any texture or format of the original base image.`,

  espelho_dagua: `Still water mirror pool with perfect architectural reflection, zen reflecting pool perfectly integrated into the architectural composition. Horizontal water feature with crystal still surface.
Natural reflections of sky and architecture on the water surface, subtle caustic light patterns, realistic water material with slight surface tension visible. IMPORTANT: Do not alter any texture or format of the original base image.`,

  // ─────────────────────────────────────────────
  // ENTORNO
  // ─────────────────────────────────────────────

  entorno_residencial: `Render the surrounding residential context visible in the scene — neighboring houses, low-rise buildings, front yards, garden walls, fences, parked vehicles on street, sidewalks, utility poles, and residential street infrastructure — all at full photographic fidelity consistent with the scale and character of the primary building. Surrounding structures rendered with accurate material variation, window patterns, roofline diversity, and natural weathering appropriate to an established residential neighborhood. Street-level human activity where present — pedestrians, cyclists, parked cars — rendered with realistic scale and natural positioning. Ambient neighborhood atmosphere conveyed through background depth, mature street trees lining sidewalks, and layered building planes receding into distance with correct atmospheric perspective. All surrounding context subordinate in visual hierarchy to the primary architectural subject, rendered with slightly reduced sharpness and contrast toward the background to reinforce depth.`,

  entorno_comercial: `Render the surrounding commercial urban context visible in the scene — mid to high-rise office buildings, retail facades, signage, commercial streetscape, wide paving, vehicle traffic, bus lanes, pedestrian flow, street furniture, and urban infrastructure — all at full photographic fidelity consistent with the density and character of a commercial district. Surrounding buildings rendered with accurate curtain wall glazing, cladding variation, mechanical penthouses, and illuminated signage where appropriate to lighting conditions. Street level populated with pedestrians in motion, commercial vehicles, taxis, and parked cars rendered at realistic scale. Urban background rendered with correct atmospheric haze and depth falloff — foreground context sharp and detailed, mid-ground buildings with reduced contrast, distant skyline fading into atmospheric perspective. All surrounding commercial context rendered as a credible, living urban environment while remaining visually subordinate to the primary architectural subject.`,

  entorno_vegetacao: `Render the surrounding natural landscape context visible in the scene — mature trees, forest edge, dense vegetation layers, ground cover, wild grasses, shrubs, and organic terrain — all at full photographic fidelity with species-appropriate silhouette, leaf translucency, branching structure, and natural color variation. Vegetation rendered with accurate response to the active lighting conditions — direct sunlight producing leaf backlight and dappled shadow patterns on ground, overcast conditions producing even muted green tones, golden hour producing warm amber rim light on canopy edges. No two trees identical — natural variation in height, crown shape, and seasonal color present throughout. Ground plane beneath vegetation rendered with leaf litter, exposed roots, moss, and soil texture appropriate to a naturalistic setting. Background vegetation fading into atmospheric depth with correct color desaturation and contrast reduction toward the horizon. All natural context rendered as a cohesive living landscape, reinforcing the integration of architecture within its natural environment.`,

  entorno_predios: `Render the surrounding mid and high-rise building context visible in the scene — apartment towers, mixed-use residential blocks, commercial ground floors, rooftop water tanks, mechanical equipment penthouses, and dense urban street infrastructure — all at full photographic fidelity consistent with the scale and vertical density of a consolidated urban district. Surrounding buildings rendered with accurate facade variation — curtain wall glazing, precast concrete panels, ceramic tile cladding, painted render, exposed concrete — each block with individual window pattern, balcony rhythm, and roofline treatment. Ground floor level rendered with commercial activity, retail awnings, building entrances, intercom panels, and pedestrian flow at street scale. Urban street infrastructure present — wide sidewalks, traffic signals, bus stops, parked vehicles, delivery trucks, and lane markings. Rooftop silhouettes of surrounding towers layered against sky in correct perspectival recession, distant buildings fading into atmospheric haze with progressive contrast and detail reduction toward the horizon. All surrounding urban context rendered as a dense, inhabited, and credible cityscape while remaining visually subordinate to the primary architectural subject through depth-of-field falloff and atmospheric perspective.`,

  entorno_casas: `Render the surrounding residential house context visible in the scene — single-family homes of varied architectural styles, low perimeter walls, front gardens, driveways, garage doors, mailboxes, sidewalks, and residential street details — all at full photographic fidelity consistent with the scale and material character of a consolidated residential neighborhood. Each neighboring house rendered with individual material variation — painted render, exposed brick, timber cladding, ceramic tile roofing, metal sheet roofing — no two houses identical in finish or architectural detailing. Front yards with mature planted gardens, lawn areas, ornamental hedges, and specimen trees providing natural screening between properties. Parked vehicles in driveways and along street curb rendered at correct residential scale. Street surface with asphalt texture, painted lane markings, speed humps, and kerb detail. Overhead utility lines and residential-scale street lighting where consistent with neighborhood character. All surrounding houses rendered with natural weathering, slight facade aging, and the accumulated material patina of an inhabited neighborhood, while remaining visually subordinate to the primary architectural subject through controlled background depth and atmospheric falloff.`,

  // ─────────────────────────────────────────────
  // QUALIDADE / ESTILO DO RENDER
  // ─────────────────────────────────────────────

  fotorrealista: `Final render quality: photorealistic, 8K ultra-high resolution, physically-based rendering pipeline, ray-traced global illumination and reflections, accurate Fresnel response on glass and polished surfaces, micro-surface roughness variation on matte materials, sub-surface scattering on organic elements. Camera simulation: Canon EOS R5, 35mm prime lens, F4 aperture, ISO 200, correct exposure metering. Post-processing: subtle film grain at 4%, slight vignette, chromatic aberration consistent with real lens optics. Output indistinguishable from on-site professional architectural photography.`,

  classico: `Final render quality: clean academic architectural presentation standard, neutral color grading with slight warm bias, soft shadows with no extreme contrast or mood manipulation, all materials rendered with technical accuracy and full color fidelity, balanced symmetric or harmonious composition, sky neutral and non-distracting, vegetation as calm green mass. Output equivalent to AIA portfolio submission or RIBA award documentation quality.`,

  atmosferico: `Final render quality: cinematic editorial grade, strong foreground-to-background depth layering, lifted blacks and crushed highlights for dramatic tonal range, rich color grading with intentional mood bias, deep shadow zones with selective ambient fill, composition with strong diagonal movement and deliberate negative space. Output equivalent to Dezeen, ArchDaily, or Wallpaper* architectural editorial photography standard, referencing the work of Iwan Baan or Hufton+Crow.`,

 
  minimalista: `Final render quality: stripped-back minimalist presentation, architecture isolated against a neutral pale or white overcast sky, ground plane in uniform light tone, all contextual distraction reduced to near zero, color palette limited to the architecture's own material range with no supplementary color. Composition centered with generous negative space. Vegetation if present reduced to a single restrained specimen. Output referencing the stillness and precision of Tadao Ando documentation and John Pawson project photography.`,
 
  // ─────────────────────────────────────────────
  // CÂMERA / PERSPECTIVA
  // ─────────────────────────────────────────────
 
  eye_level: `Camera positioned at standard human eye level, 1.6 meters above ground plane, horizontal sight line parallel to floor, natural standing-person perspective. Focal length equivalent to 35mm to 50mm lens, replicating natural human field of vision with no vertical distortion. Ground plane visible in lower third of frame, sky or ceiling in upper third, architecture occupying the full vertical middle zone. This is the most natural and immediately relatable viewing angle for residential and commercial architecture — the way any person standing on site would perceive the building.`,
 
  worm_eye: `Camera positioned extremely low, 10 to 20 centimeters above ground plane, lens tilted upward toward the building. Strong converging vertical lines running from base of building upward, exaggerating building height and structural mass. Ground plane occupies foreground as a dominant textured surface in sharp focus. Sky fills a large proportion of upper frame. Overhangs, soffits, underside of balconies, cantilevered volumes, and structural columns become primary compositional elements. Focal length equivalent to 20mm to 24mm wide angle to maximize vertical drama. This angle communicates power, monumentality, and structural ambition.`,
 
  bird_eye: `Camera positioned directly overhead or at a high oblique angle between 60 and 90 degrees downward, simulating aerial or elevated observation point. Full site footprint visible — roof planes, terraces, landscaping, pool, driveway, surrounding context, and street geometry all readable simultaneously. Roof material, parapet details, rooftop equipment, and plan organization legible from above. Ground-level context including neighboring structures, trees, and hardscape visible for scale and orientation. Focal length equivalent to 24mm to 35mm. This angle communicates site strategy, massing logic, roof design, and the relationship of the building to its urban or natural surroundings.`,
 
  dutch_angle: `Camera rotated on its longitudinal axis between 15 and 35 degrees from horizontal, producing a deliberate diagonal tilt across the entire frame. Horizon line runs diagonally rather than horizontally, all vertical architectural elements — columns, walls, window frames — rendered at an angle relative to the frame edges. This creates visual tension, dynamic energy, and cinematic unease. Compositional diagonals reinforce the tilt, with strong leading lines running corner to corner. Focal length equivalent to 24mm to 35mm. Best applied to editorial, atmospheric, or concept renders where mood and dramatic impact take priority over technical legibility. Avoid for presentation drawings requiring architectural accuracy.`,
 
  wide_angle: `Camera fitted with an ultra-wide angle lens equivalent to 14mm to 20mm focal length, capturing an expanded horizontal and vertical field of view in a single frame. Strong barrel distortion or deliberately corrected rectilinear perspective depending on desired effect. Foreground elements appear larger and more prominent relative to background, exaggerating spatial depth and distance between near and far planes. Tight interior spaces appear expansive and generous. Exterior shots capture full building width plus substantial surrounding context within a single composition. Vertical lines at frame edges may converge or diverge — correct with tilt-shift simulation for formal presentation, or retain for dynamic editorial effect. This angle is ideal for communicating spatial generosity, site context, and architectural scale in a single image.`,
 
  // ─────────────────────────────────────────────
  // SUFIXO TÉCNICO UNIVERSAL
  // ─────────────────────────────────────────────
 
  suffix: `Rendered with full physically-based rendering pipeline, ray-traced global illumination, HDRI sky lighting, accurate Fresnel reflectivity on all surfaces, micro-surface roughness variation, contact shadows and ambient occlusion at every junction. Camera simulation: full-frame sensor, 35mm prime lens, F5.6 aperture, ISO 100, 1/250s, correct exposure metering with no blown highlights and full shadow detail retained. Color grading: neutral LUT with slight warm bias, contrast curve lifted at midtones, no artificial saturation boost. Output sharpness equivalent to medium-format architectural photography. Subtle film grain at 3%, real lens vignette, no HDR halo artifacts. The final image must be indistinguishable from a photograph taken on location by a professional architectural photographer. --ar 16:9 --q 2 --v 6.1 --style raw`
 
}
 
// ─────────────────────────────────────────────
// MAPEAMENTO: combinações render + iluminação
// Usado internamente para selecionar o prompt correto
// conforme tipo de render + período selecionados
// ─────────────────────────────────────────────
 
export const PROMPT_COMBINATIONS: Record<string, string> = {
  "render_externo+diurno":      RENDER_PROMPTS.render_externo + " " + RENDER_PROMPTS.diurno,
  "render_externo+entardecer":  RENDER_PROMPTS.render_externo + " " + RENDER_PROMPTS.entardecer,
  "render_externo+noturno":     RENDER_PROMPTS.render_externo + " " + RENDER_PROMPTS.noturno,
  "render_externo+nublado":     RENDER_PROMPTS.render_externo + " " + RENDER_PROMPTS.nublado,
  "render_externo+chuva":       RENDER_PROMPTS.render_externo + " " + RENDER_PROMPTS.chuva,
  "render_externo+amanhecer":   RENDER_PROMPTS.render_externo + " " + RENDER_PROMPTS.amanhecer,
  "render_interno+diurno":      RENDER_PROMPTS.render_interno + " " + RENDER_PROMPTS.diurno,
  "render_interno+entardecer":  RENDER_PROMPTS.render_interno + " " + RENDER_PROMPTS.entardecer,
  "render_interno+noturno":     RENDER_PROMPTS.render_interno + " " + RENDER_PROMPTS.noturno,
  "render_interno+nublado":     RENDER_PROMPTS.render_interno + " " + RENDER_PROMPTS.nublado,
  "render_interno+chuva":       RENDER_PROMPTS.render_interno + " " + RENDER_PROMPTS.chuva,
  "render_interno+amanhecer":   RENDER_PROMPTS.render_interno + " " + RENDER_PROMPTS.amanhecer,
}
 
// ─────────────────────────────────────────────
// HUMANIZAÇÃO
// ─────────────────────────────────────────────
 
export const HUMANIZATION_PROMPT = (pessoas: string, animais: string) => {
  const parts: string[] = ["Add lifestyle humanization to the architectural scene:"];
  if (pessoas) {
    parts.push("Human presence: " + pessoas + ". People must look completely natural, candid lifestyle photography style, well-integrated into the architectural setting, not posed or artificial, photorealistic human figures with realistic clothing, skin tones and natural body language, appropriate scale to architecture, no plastic or synthetic appearance.");
  }
  if (animais) {
    parts.push("Animal presence: " + animais + ". Animals in natural relaxed behavior, photorealistic fur/skin textures, harmoniously integrated into the landscape, correct scale to environment, natural posture and expression.");
  }
  parts.push("All humanization elements must be indistinguishable from a real photograph. Do not alter the original architecture, layout or materials.");
  return parts.join("\n");
}
