-- Sync generation_sessions table with database structure
-- The database has many more columns than the migration file

-- Add missing columns to generation_sessions table
ALTER TABLE public.generation_sessions 
  ADD COLUMN IF NOT EXISTS session_token TEXT,
  ADD COLUMN IF NOT EXISTS original_image_url TEXT,
  ADD COLUMN IF NOT EXISTS original_image_name TEXT,
  ADD COLUMN IF NOT EXISTS original_image_size INTEGER,
  ADD COLUMN IF NOT EXISTS original_image_type TEXT,
  ADD COLUMN IF NOT EXISTS image_analysis JSONB,
  ADD COLUMN IF NOT EXISTS analysis_model TEXT,
  ADD COLUMN IF NOT EXISTS prompt_text TEXT,
  ADD COLUMN IF NOT EXISTS render_config JSONB DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS generated_image_url TEXT,
  ADD COLUMN IF NOT EXISTS generated_image_name TEXT,
  ADD COLUMN IF NOT EXISTS generated_image_size INTEGER,
  ADD COLUMN IF NOT EXISTS generated_image_type TEXT,
  ADD COLUMN IF NOT EXISTS render_metadata JSONB DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS error_message TEXT,
  ADD COLUMN IF NOT EXISTS tokens_used INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS processing_time_ms INTEGER,
  ADD COLUMN IF NOT EXISTS cost_brl NUMERIC(10,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS api_provider TEXT,
  ADD COLUMN IF NOT EXISTS model_used TEXT,
  ADD COLUMN IF NOT EXISTS batch_id UUID,
  ADD COLUMN IF NOT EXISTS is_batch BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS shared_prompt_id UUID REFERENCES public.shared_prompts(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS collection_id UUID REFERENCES public.collections(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS favorited_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS exported_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS watermark_removed BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS quality_score NUMERIC(3,2),
  ADD COLUMN IF NOT EXISTS user_rating INTEGER CHECK (user_rating BETWEEN 1 AND 5),
  ADD COLUMN IF NOT EXISTS feedback TEXT,
  ADD COLUMN IF NOT EXISTS tags TEXT[],
  ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS retry_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_retries INTEGER DEFAULT 3,
  ADD COLUMN IF NOT EXISTS next_retry_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS webhook_url TEXT,
  ADD COLUMN IF NOT EXISTS webhook_payload JSONB,
  ADD COLUMN IF NOT EXISTS webhook_status TEXT,
  ADD COLUMN IF NOT EXISTS webhook_attempts INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS webhook_response JSONB;
